server: 
  port: 7006


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
    
webhook:
  url:  https://hooks.slack.com/services/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